patterns:
- aten::sym_numel
- aten::view_copy
- aten::permute_copy
- aten::reshape
- aten::mul_
- aten::_assert_async
- aten::reshape_copy
- aten::item
- aten::flatten_copy
- aten::unsqueeze_
- aten::new_zeros
- aten::_convolution
- aten::empty_like
- aten::t
- torch::autograd::AccumulateGrad
- aten::sym_storage_offset
- aten::chunk_copy
- aten::transpose_copy
- aten::squeeze_
- aten::warn
- aten::_batch_norm_impl_index
- aten::max_pool2d_with_indices_backward
- aten::empty
- aten::narrow
- aten::narrow_copy
- aten::split_copy
- aten::new_full
- aten::addcdiv_
- aten::lift_fresh
- aten::copy_
- aten::detach
- aten::lerp_
- aten::flatten
- aten::call
- aten::zeros
- aten::zero_
- aten::new_ones
- aten::split
- aten::resolve_neg
- aten::expand
- aten::expand_copy
- aten::nll_loss_forward
- aten::unsqueeze_copy
- aten::squeeze_copy
- aten::is_nonzero
- aten::is_pinned
- aten::contiguous
- aten::native_batch_norm_backward
- aten::view
- aten::unbind
- aten::threshold_backward
- aten::resize_
- aten::set_
- aten::zeros_like
- aten::_log_softmax
- aten::full
- aten::_to_copy
- aten::as_strided_
- aten::select
- aten::slice
- aten::tolist
- aten::addcmul_
- aten::ones
- aten::add_
- aten::empty_strided
- aten::to
- aten::squeeze
- aten::nll_loss_nd
- aten::_pin_memory
- aten::pin_memory
- aten::cross_entropy_loss
- aten::convolution_backward
- aten::slice_copy
- aten::chunk
- aten::ones_like
- aten::fill_
- aten::__interpolate
- aten::unbind_copy
- aten::transpose
- aten::new_empty
- aten::permute
- aten::_has_compatible_shallow_copy_type
- aten::select_copy
- aten::_log_softmax_backward_data
- aten::unsqueeze
- aten::nll_loss_backward
- aten::full_like
- aten::_local_scalar_dense
- aten::sym_size
- aten::resolve_conj
- aten::div_
- aten::_reshape_alias
- aten::sym_stride
- aten::as_strided
- aten::clone
